import { useState, type FormEvent } from "react";
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, Plus, Save, Trash2 } from "lucide-react";

import { createAdminBrandFn, createAdminProductFn, getAdminCompanyDetail, updateAdminCompanyFn, updateAdminProductFn } from "@/lib/api/catalog-admin.functions";
import { readCsrfToken } from "@/lib/admin-csrf";

export const Route = createFileRoute("/admin/catalog/companies/$companyId")({
  loader: ({ params }) => getAdminCompanyDetail({ data: { companyId: params.companyId } }),
  component: CompanyDetailPage,
});

type VariantForm = { id?: string; name: string; supplierSku: string; packaging: string; factoryPrice: string; markupPercent: string; sellingPrice: string; pricingMethod: "MARKUP_PERCENT" | "FIXED_SELLING_PRICE" };
type PublicationStatus = "DRAFT" | "IN_REVIEW" | "PUBLISHED" | "ARCHIVED";
const emptyVariant = (): VariantForm => ({ name: "", supplierSku: "", packaging: "", factoryPrice: "", markupPercent: "", sellingPrice: "", pricingMethod: "MARKUP_PERCENT" });

function CompanyDetailPage() {
  const result = Route.useLoaderData();
  const navigate = useNavigate();
  const company = result.ok ? result.company : null;
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const [showProduct, setShowProduct] = useState(false);
  const [editingProduct, setEditingProduct] = useState<string | null>(null);
  const [companyForm, setCompanyForm] = useState(() => ({ displayName: company?.displayName ?? "", legalName: company?.legalName ?? "", countryCode: company?.countryCode ?? "", website: company?.website ?? "", internalNotes: company?.internalNotes ?? "", status: company?.status ?? "ACTIVE" }));
  const [productForm, setProductForm] = useState<{ name: string; shortDescription: string; description: string; internalNotes: string; brandId: string; taxonomyNodeId: string; countryOfOrigin: string; publicationStatus: PublicationStatus; variants: VariantForm[] }>({ name: "", shortDescription: "", description: "", internalNotes: "", brandId: "", taxonomyNodeId: "", countryOfOrigin: "DZ", publicationStatus: "DRAFT", variants: [emptyVariant()] });

  if (!company) return <div className="p-6 text-red-700">{result.error}</div>;
  const csrf = { "x-wossol-csrf": readCsrfToken() ?? "" };
  const refresh = () => navigate({ to: "/admin/catalog/companies/$companyId", params: { companyId: company.id }, replace: true });
  const price = (value: string) => value === "" ? null : Number(value);
  const saveCompany = async (event: FormEvent) => {
    event.preventDefault(); setSaving(true); setError("");
    try { const response = await updateAdminCompanyFn({ data: { companyId: company.id, data: companyForm }, headers: csrf }); if (!response.ok) setError(response.error); else await refresh(); } catch { setError("Company could not be saved."); } finally { setSaving(false); }
  };
  const saveProduct = async (event: FormEvent) => {
    event.preventDefault(); setSaving(true); setError("");
    const data = { ...productForm, brandId: productForm.brandId || null, taxonomyNodeId: productForm.taxonomyNodeId || null, variants: productForm.variants.map((variant) => ({ ...variant, packaging: { details: variant.packaging }, factoryPrice: price(variant.factoryPrice), markupPercent: price(variant.markupPercent), sellingPrice: price(variant.sellingPrice), publicationStatus: productForm.publicationStatus })) };
    try {
      const response = editingProduct ? await updateAdminProductFn({ data: { companyId: company.id, productId: editingProduct, data }, headers: csrf }) : await createAdminProductFn({ data: { companyId: company.id, data }, headers: csrf });
      if (!response.ok) setError(response.error); else { setShowProduct(false); setEditingProduct(null); setProductForm({ name: "", shortDescription: "", description: "", internalNotes: "", brandId: "", taxonomyNodeId: "", countryOfOrigin: "DZ", publicationStatus: "DRAFT", variants: [emptyVariant()] }); await refresh(); }
    } catch { setError("Product could not be saved."); } finally { setSaving(false); }
  };
  const editProduct = (product: typeof company.products[number]) => { setEditingProduct(product.id); setProductForm({ name: product.name, shortDescription: product.shortDescription ?? "", description: product.description ?? "", internalNotes: product.internalNotes ?? "", brandId: product.brandId ?? "", taxonomyNodeId: product.taxonomyNodeId ?? "", countryOfOrigin: product.countryOfOrigin, publicationStatus: product.publicationStatus, variants: product.variants.map((variant) => ({ id: variant.id, name: variant.name ?? "", supplierSku: variant.supplierSku ?? variant.sku, packaging: typeof variant.packaging === "object" && variant.packaging && "details" in variant.packaging ? String((variant.packaging as { details: unknown }).details) : "", factoryPrice: variant.factoryPrice ?? "", markupPercent: variant.markupPercent ?? "", sellingPrice: variant.sellingPrice ?? "", pricingMethod: variant.pricingMethod ?? "FIXED_SELLING_PRICE" })) }); setShowProduct(true); };
  return <div className="mx-auto max-w-6xl space-y-6"><Link to="/admin/catalog/companies" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600"><ArrowLeft className="h-4 w-4" /> Companies</Link><div><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-600">Company catalog</p><h1 className="mt-2 text-3xl font-semibold">{company.displayName}</h1></div>{error && <p className="rounded bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <form onSubmit={saveCompany} className="rounded-xl border bg-white p-5"><div className="flex justify-between"><h2 className="font-semibold">Company information</h2><button disabled={saving} className="inline-flex items-center gap-2 rounded bg-slate-900 px-3 py-2 text-sm font-semibold text-white"><Save className="h-4 w-4" /> Save</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Input label="Display name" value={companyForm.displayName} onChange={(displayName) => setCompanyForm({ ...companyForm, displayName })} required /><Input label="Legal name" value={companyForm.legalName} onChange={(legalName) => setCompanyForm({ ...companyForm, legalName })} /><Input label="Country code" value={companyForm.countryCode} onChange={(countryCode) => setCompanyForm({ ...companyForm, countryCode })} /><Input label="Website" value={companyForm.website} onChange={(website) => setCompanyForm({ ...companyForm, website })} /></div></form>
    <section className="rounded-xl border bg-white"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-semibold">Products</h2><p className="text-sm text-slate-500">Products belong directly to this Company. Brand is optional.</p></div><button onClick={() => { setEditingProduct(null); setShowProduct(true); }} className="inline-flex items-center gap-2 rounded bg-amber-500 px-3 py-2 text-sm font-semibold"><Plus className="h-4 w-4" /> Add product</button></div>
      {showProduct && <form onSubmit={saveProduct} className="space-y-4 border-b bg-slate-50 p-5"><h3 className="font-semibold">{editingProduct ? "Edit product" : "Add product"}</h3><div className="grid gap-3 sm:grid-cols-2"><Input label="Product name" value={productForm.name} onChange={(name) => setProductForm({ ...productForm, name })} required /><label className="text-sm">Optional brand<select value={productForm.brandId} onChange={(event) => setProductForm({ ...productForm, brandId: event.target.value })} className="mt-1 block h-10 w-full rounded border px-3"><option value="">No brand</option>{company.brands.map((brand) => <option key={brand.id} value={brand.id}>{brand.name}</option>)}</select></label><Input label="Taxonomy node ID (optional until taxonomy import)" value={productForm.taxonomyNodeId} onChange={(taxonomyNodeId) => setProductForm({ ...productForm, taxonomyNodeId })} /><Input label="Country of origin" value={productForm.countryOfOrigin} onChange={(countryOfOrigin) => setProductForm({ ...productForm, countryOfOrigin })} /></div><Input label="Short description" value={productForm.shortDescription} onChange={(shortDescription) => setProductForm({ ...productForm, shortDescription })} />
        <div><h4 className="font-semibold">Variants / SKUs</h4>{productForm.variants.map((variant, index) => <div key={index} className="mt-3 grid gap-3 rounded border bg-white p-3 sm:grid-cols-3"><Input label="Variant name" value={variant.name} onChange={(name) => setProductForm({ ...productForm, variants: productForm.variants.map((item, itemIndex) => itemIndex === index ? { ...item, name } : item) })} /><Input label="Supplier SKU" value={variant.supplierSku} onChange={(supplierSku) => setProductForm({ ...productForm, variants: productForm.variants.map((item, itemIndex) => itemIndex === index ? { ...item, supplierSku } : item) })} /><Input label="Packaging / supply details" value={variant.packaging} onChange={(packaging) => setProductForm({ ...productForm, variants: productForm.variants.map((item, itemIndex) => itemIndex === index ? { ...item, packaging } : item) })} /><label className="text-sm">Pricing mode<select value={variant.pricingMethod} onChange={(event) => setProductForm({ ...productForm, variants: productForm.variants.map((item, itemIndex) => itemIndex === index ? { ...item, pricingMethod: event.target.value as VariantForm["pricingMethod"] } : item) })} className="mt-1 block h-10 w-full rounded border px-3"><option value="MARKUP_PERCENT">Markup %</option><option value="FIXED_SELLING_PRICE">Fixed selling price</option></select></label><Input label="Factory price (DZD)" value={variant.factoryPrice} onChange={(factoryPrice) => setProductForm({ ...productForm, variants: productForm.variants.map((item, itemIndex) => itemIndex === index ? { ...item, factoryPrice } : item) })} /><Input label={variant.pricingMethod === "MARKUP_PERCENT" ? "Markup %" : "Selling price (DZD)"} value={variant.pricingMethod === "MARKUP_PERCENT" ? variant.markupPercent : variant.sellingPrice} onChange={(value) => setProductForm({ ...productForm, variants: productForm.variants.map((item, itemIndex) => itemIndex === index ? variant.pricingMethod === "MARKUP_PERCENT" ? { ...item, markupPercent: value } : { ...item, sellingPrice: value } : item) })} />{productForm.variants.length > 1 && <button type="button" onClick={() => setProductForm({ ...productForm, variants: productForm.variants.filter((_, itemIndex) => itemIndex !== index) })} className="text-sm text-red-700"><Trash2 className="inline h-4 w-4" /> Remove variant</button>}</div>)}<button type="button" onClick={() => setProductForm({ ...productForm, variants: [...productForm.variants, emptyVariant()] })} className="mt-3 text-sm font-semibold text-slate-700"><Plus className="inline h-4 w-4" /> Add variant</button></div><div className="flex gap-2"><button disabled={saving} className="rounded bg-slate-900 px-3 py-2 text-sm font-semibold text-white">{saving ? "Saving…" : "Save product"}</button><button type="button" onClick={() => setShowProduct(false)} className="rounded border px-3 py-2 text-sm">Cancel</button></div></form>}
      <div className="divide-y">{company.products.map((product) => <div key={product.id} className="flex items-center justify-between p-5"><div><p className="font-medium">{product.name}</p><p className="text-sm text-slate-500">{product.variants.length} SKU{product.variants.length === 1 ? "" : "s"} · {product.publicationStatus.toLowerCase()}</p></div><button onClick={() => editProduct(product)} className="text-sm font-semibold underline">Edit product</button></div>)}{company.products.length === 0 && <p className="p-5 text-sm text-slate-500">No products yet.</p>}</div></section></div>;
}

function Input({ label, value, onChange, required = false }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) { return <label className="text-sm">{label}<input required={required} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 block h-10 w-full rounded border px-3" /></label>; }
