import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Boxes, Check, MessageCircle, ShieldCheck, Workflow } from "lucide-react";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "Wossol Platform | Merchant operations" }, { name: "description", content: "Wossol Platform supports merchant operations and connected commerce workflows." }, { property: "og:title", content: "Wossol Platform | Merchant operations" }, { property: "og:description", content: "A focused platform for merchant operations and connected commerce workflows." }] }), component: Home });

function Home() {
  return <>
    <section className="relative overflow-hidden bg-deep-navy text-deep-navy-foreground"><div className="absolute -right-32 -top-32 h-96 w-96 rounded-full bg-gold/10 blur-3xl" /><div className="relative container-page grid gap-12 py-20 md:grid-cols-[1.1fr_.9fr] md:items-center md:py-28"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-gold">Merchant operations platform</p><h1 className="mt-5 max-w-3xl text-4xl font-semibold leading-[1.08] tracking-tight md:text-6xl">Commerce operations, connected with care.</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-deep-navy-foreground/75">Wossol Platform is being developed to support merchant commerce and operational workflows across connected business services.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#capabilities" className="inline-flex items-center gap-2 rounded-md bg-gold px-5 py-3 text-sm font-semibold text-gold-foreground transition-colors hover:bg-gold/90">Explore the platform <ArrowRight className="h-4 w-4" /></a><Link to="/privacy-policy" className="inline-flex items-center rounded-md border border-deep-navy-foreground/25 px-5 py-3 text-sm font-semibold text-deep-navy-foreground transition-colors hover:border-gold hover:text-gold">Read our Privacy Policy</Link></div></div><div className="rounded-2xl border border-deep-navy-foreground/15 bg-deep-navy-foreground/[.06] p-6 shadow-[var(--shadow-elevated)] md:p-8"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-gold">Built around bounded workflows</p><div className="mt-6 space-y-5">{["Merchant-scoped connections", "Operational events, not an inbox", "Human-controlled order creation"].map((item) => <div key={item} className="flex items-start gap-3"><span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-gold/20 text-gold"><Check className="h-3.5 w-3.5" /></span><span className="text-sm text-deep-navy-foreground/85">{item}</span></div>)}</div></div></div></section>
    <section id="capabilities" className="section-pad bg-background"><div className="container-page"><div className="max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-gold">What Wossol supports</p><h2 className="mt-3 text-3xl font-semibold text-navy md:text-4xl">Focused infrastructure for real merchant work.</h2><p className="mt-4 text-base leading-relaxed text-muted-foreground">The public site intentionally describes the platform at a high level. Product capabilities and integrations remain scoped to the workflows supported by the implementation.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[{ icon: Workflow, title: "Commerce workflows", text: "A foundation for merchant operations and connected commerce processes." }, { icon: MessageCircle, title: "Business messaging", text: "Supported provider events can contribute to bounded operational workflows." }, { icon: ShieldCheck, title: "Scoped by design", text: "Connections and operational data are scoped to the relevant merchant or workspace." }].map(({ icon: Icon, title, text }) => <article key={title} className="rounded-xl border border-border bg-card p-6 shadow-[var(--shadow-card)]"><span className="grid h-11 w-11 place-items-center rounded-lg bg-gold/15 text-navy"><Icon className="h-5 w-5" /></span><h3 className="mt-5 text-lg font-semibold text-navy">{title}</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{text}</p></article>)}</div></div></section>
    <section className="section-pad bg-off-white"><div className="container-page grid gap-8 md:grid-cols-[.8fr_1.2fr] md:items-center"><div><Boxes className="h-9 w-9 text-gold" /><h2 className="mt-4 text-3xl font-semibold text-navy">Clear boundaries matter.</h2></div><div className="space-y-4 text-sm leading-relaxed text-muted-foreground"><p>Wossol does not present itself as a general-purpose messaging inbox. Native messaging applications remain the merchant’s normal messaging surface.</p><p>For Messaging V1, a merchant-authored <code className="rounded bg-white px-1.5 py-0.5 text-navy">#WOSSOL</code> handoff marker may support an Order Capture Candidate. A candidate is not automatically an Order; the merchant completes the normal Create Order workflow.</p><Link to="/privacy-policy" className="inline-flex items-center gap-2 font-semibold text-navy hover:text-gold">How data is handled <ArrowRight className="h-4 w-4" /></Link></div></div></section>
  </>;
}
