import { ArrowLeft, ExternalLink } from "lucide-react";
import { useState, type ReactNode } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { getAdminPipelineCompanyFn } from "@/lib/api/pipeline-search.functions";
import { countryLabel } from "@/lib/countries";
import { safeWebsiteHref } from "@/lib/pipeline-search";

export const Route = createFileRoute("/admin/search/$companyId")({ loader: ({ params }) => getAdminPipelineCompanyFn({ data: { companyId: params.companyId } }), component: PipelineCompanyDetailPage });
const tabs = ["overview", "contacts", "tracking", "outreach", "communications", "audit"] as const;
type Tab = (typeof tabs)[number];
function pretty(value: string | null | undefined) { return value ? value.replaceAll("_", " ").toLowerCase().replace(/(^| )\w/g, (letter) => letter.toUpperCase()) : "—"; }
function statusTone(value: string | null | undefined) { if (["SENT", "VERIFIED", "COMPLETED", "REPLIED", "DATA_RECEIVED"].includes(value ?? "")) return "bg-emerald-100 text-emerald-800"; if (["FAILED", "UNVERIFIED", "REFUSED", "UNREACHABLE"].includes(value ?? "")) return "bg-rose-100 text-rose-800"; return "bg-slate-100 text-slate-700"; }

function PipelineCompanyDetailPage() {
  const result = Route.useLoaderData(); const [tab, setTab] = useState<Tab>("overview");
  if (!result.ok) return <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-sm text-red-800">{result.error}</div>;
  const company = result.company; const websiteHref = safeWebsiteHref(company.website);
  return <div className="mx-auto max-w-7xl space-y-6"><Link to="/admin/search" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 hover:text-slate-950"><ArrowLeft className="h-4 w-4" /> Back to Pipeline Search</Link>
    <header className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-4 md:flex-row"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-amber-600">Pipeline company</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">{company.summary.name}</h1><p className="mt-2 font-mono text-xs text-slate-500">{company.companyId}</p></div><div className="flex flex-wrap gap-2"><Badge value={company.summary.commercialStatus} /><Badge value={company.summary.attention} /><Badge value={company.replyStatus} /></div></div><div className="mt-6 grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><Info label="Country" value={countryLabel(company.countryCode) || company.countryRaw} /><Info label="Sector" value={company.sector} /><Info label="Email outreach" value={company.summary.emailOutreachStatus} /><Info label="Last contact" value={company.lastContactAt} /><Info label="Next follow-up" value={company.nextFollowUpAt} /><Info label="Current action" value={pretty(company.currentAction)} /><Info label="Lifecycle" value={pretty(company.lifecycleStatus)} />{websiteHref ? <Info label="Website" value={company.website} href={websiteHref} /> : <Info label="Website" value={company.website} />}</div></header>
    <nav className="flex gap-1 overflow-x-auto rounded-xl border border-slate-200 bg-white p-2 shadow-sm" aria-label="Company detail tabs">{tabs.map((item) => <button key={item} type="button" onClick={() => setTab(item)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-semibold transition ${tab === item ? "bg-[#102c50] text-white" : "text-slate-600 hover:bg-slate-100"}`}>{item === "tracking" ? "Tracking / Activity" : pretty(item)}</button>)}</nav>
    {tab === "overview" && <Overview company={company} />}{tab === "contacts" && <Contacts company={company} />}{tab === "tracking" && <Tracking company={company} />}{tab === "outreach" && <Outreach company={company} />}{tab === "communications" && <Communications company={company} />}{tab === "audit" && <Audit company={company} />}
  </div>;
}

function Overview({ company }: { company: any }) { return <div className="grid gap-6 lg:grid-cols-2"><Section title="Company identity"><dl className="grid gap-4 sm:grid-cols-2"><Info label="Legal name" value={company.legalName} /><Info label="Trade name" value={company.tradeName} /><Info label="Location" value={[company.city, company.wilaya, company.address].filter(Boolean).join(" · ")} /><Info label="Contact person" value={[company.contactPerson, company.department].filter(Boolean).join(" · ")} /><Info label="Email" value={company.email} /><Info label="Phone" value={company.phone} /><Info label="WhatsApp" value={company.whatsapp} /><Info label="Discovery source" value={company.discoverySource} /></dl></Section><Section title="Commercial progress"><dl className="grid gap-4 sm:grid-cols-2"><Info label="Qualification" value={pretty(company.qualificationStatus)} /><Info label="Commercial status" value={pretty(company.summary.commercialStatus)} /><Info label="Reply status" value={pretty(company.replyStatus)} /><Info label="Attention" value={pretty(company.summary.attention)} /><Info label="Next action" value={pretty(company.currentAction)} /><Info label="Next follow-up" value={company.nextFollowUpAt} /><Info label="Catalog received" value={company.catalogReceived ? "Yes" : "No"} /><Info label="Prices received" value={company.pricesReceived ? "Yes" : "No"} /></dl></Section><Section title="Classification context"><p className="text-sm text-slate-700">{company.companyCategories?.length ? company.companyCategories.map((item: any) => item.category.displayName).join(", ") : "No verified classification recorded."}</p><p className="mt-3 text-sm text-slate-500">{company.classifications?.length ? company.classifications.map((item: any) => `${item.category.displayName}: ${pretty(item.classificationStatus)}`).join(" · ") : "No evidence-backed portfolio classification recorded."}</p></Section><Section title="Source context"><Info label="Source URL" value={company.sourceUrl} /><Info label="Discovery date" value={company.discoveryDate} /><Info label="Internal notes" value={company.internalNotes} /></Section></div>; }
function Contacts({ company }: { company: any }) { return <div className="space-y-6"><Section title={`Contact points and provenance (${company.contactPoints.length})`}><Empty value={!company.contactPoints.length} text="No contact points imported." />{company.contactPoints.map((point: any) => <article key={point.contactPointId} className="border-b border-slate-100 py-4 last:border-0"><div className="flex flex-wrap items-center gap-2"><strong>{point.displayValue}</strong><Badge value={point.contactType} /><Badge value={point.verificationStatus} /><span className="text-xs text-slate-500">{point.businessFunction ?? "No business function"}</span></div><p className="mt-1 text-xs text-slate-500">{point.active ? "Active" : "Inactive"} · {point.provenance ?? "No provenance label"} · {point.sourceUrl ?? "No source URL"}</p>{point.sources.length > 0 && <ul className="mt-2 space-y-1 text-xs text-slate-600">{point.sources.map((source: any) => <li key={source.contactPointSourceId}>Evidence: {source.evidence ?? "—"} · {source.sourceUrl ?? "No URL"}</li>)}</ul>}</article>)}</Section><Section title={`Named contacts (${company.contacts.length})`}><Empty value={!company.contacts.length} text="No named contacts imported." />{company.contacts.map((contact: any) => <Record key={contact.contactId} title={contact.name ?? "Unnamed contact"} meta={contact.department ?? "No department"}><p>{contact.email ?? "No email"} · {contact.phone ?? "No phone"}</p><p className="mt-1 text-xs text-slate-500">WhatsApp: {contact.whatsapp ?? "Not recorded"}</p></Record>)}</Section></div>; }
function Tracking({ company }: { company: any }) { return <div className="space-y-6"><Section title="Tracking / Activity"><dl className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Commercial progress" value={pretty(company.summary.commercialStatus)} /><Info label="Attention" value={pretty(company.summary.attention)} /><Info label="Reply status" value={pretty(company.replyStatus)} /><Info label="Last contact" value={company.lastContactAt} /><Info label="Catalog received" value={company.catalogReceived ? "Yes" : "No"} /><Info label="Prices received" value={company.pricesReceived ? "Yes" : "No"} /><Info label="Required information" value={company.requiredInformationReceived ? "Yes" : "No"} /><Info label="Next follow-up" value={company.nextFollowUpAt} /></dl></Section><Section title={`Follow-up actions (${company.actions.length})`}><Empty value={!company.actions.length} text="No follow-up actions recorded." />{company.actions.map((action: any) => <Record key={action.actionId} title={pretty(action.actionType)} meta={`${pretty(action.status)} · ${action.dueAt ?? "No due date"}`}><p>{action.notes ?? "No action note."}</p></Record>)}</Section><Section title="Activity timeline"><Empty value={!company.communications.length} text="No communication activity recorded." />{company.communications.map((item: any) => <Record key={item.communicationId} title={`${pretty(item.channel ?? item.eventType)} · ${pretty(item.direction)}`} meta={`${item.occurredAt} · ${pretty(item.status ?? item.outcome)}`}><Text value={item.operatorSummary ?? item.body} /><p className="mt-2 text-xs text-slate-500">Exact route: {item.contactValueSnapshot ?? item.recipients ?? "Not recorded"} · Next action: {item.nextAction ?? "—"}</p></Record>)}</Section></div>; }
function Outreach({ company }: { company: any }) { return <div className="space-y-6"><Section title={`Outreach plans and drafts (${company.outreachDrafts.length})`}><Empty value={!company.outreachDrafts.length} text="No outreach drafts imported." />{company.outreachDrafts.map((draft: any) => <div key={draft.draftId} className="border-b border-slate-100 py-4 last:border-0"><div className="flex flex-wrap gap-2"><strong>{draft.draftId}</strong><Badge value={draft.status} /><span className="text-xs text-slate-500">Current version {draft.currentVersion}</span></div>{draft.versions.map((version: any) => <div key={version.versionId} className="mt-3 rounded-lg bg-slate-50 p-4"><div className="flex justify-between gap-3 text-sm font-semibold"><span>Version {version.versionNumber} · {version.channel} · {pretty(version.draftStatus)}</span><span className="text-xs text-slate-500">{version.createdAt}</span></div><p className="mt-2 font-medium">{version.subject ?? "No subject"}</p><Text value={version.externalMessage} /><details className="mt-3"><summary className="cursor-pointer text-sm font-semibold text-slate-700">Arabic operator translation</summary><Text value={version.arabicTranslation} /></details></div>)}{draft.sendPlans.map((plan: any) => <div key={plan.sendPlanId} className="mt-3 border-l-2 border-amber-400 pl-3 text-xs text-slate-600">Send plan: {pretty(plan.authorizationState)} · {pretty(plan.sendState)} · {plan.recipients.length} frozen recipient(s)</div>)}</div>)}</Section><Section title={`Send attempts (${company.sendAttempts.length})`}><Empty value={!company.sendAttempts.length} text="No send attempts imported." />{company.sendAttempts.map((attempt: any) => <Record key={attempt.sendAttemptId} title={`${pretty(attempt.status)} · ${attempt.recipient}`} meta={`${attempt.attemptAt} · ${attempt.provider}`}><Text value={attempt.externalMessage} /><p className="mt-2 text-xs text-slate-500">Provider result: {attempt.providerMessageId ?? attempt.errorMessage ?? "No provider result"}. SENT means provider acceptance, not delivery, reading or reply.</p></Record>)}</Section></div>; }
function Communications({ company }: { company: any }) { return <Section title={`Communications (${company.communications.length})`}><Empty value={!company.communications.length} text="No communications imported." />{company.communications.map((item: any) => <Record key={item.communicationId} title={`${pretty(item.direction)} · ${pretty(item.channel ?? item.eventType)}`} meta={`${item.occurredAt} · ${pretty(item.status ?? item.outcome)}`}><p className="font-semibold">{item.subject ?? "No subject"}</p><Text value={item.body} /><p className="mt-2 text-xs text-slate-500">Outcome: {item.outcome ?? "—"} · Commercial result: {item.commercialResult ?? "—"} · Reply status is tracked separately.</p></Record>)}</Section>; }
function Audit({ company }: { company: any }) { return <div className="space-y-6"><Section title={`Audit history (${company.auditEvents.length})`}><Empty value={!company.auditEvents.length} text="No audit events imported." />{company.auditEvents.map((event: any) => <Record key={event.auditId} title={pretty(event.eventType)} meta={event.createdAt}><Text value={event.details} /><p className="mt-2 text-xs text-slate-500">{event.reason ?? "No reason recorded"}</p></Record>)}</Section><Section title={`Discovery evidence (${company.discoveryEvents.length})`}><Empty value={!company.discoveryEvents.length} text="No discovery evidence imported." />{company.discoveryEvents.map((event: any) => <Record key={event.eventId} title={`${pretty(event.outcome)} · ${pretty(event.duplicateStatus)}`} meta={`${event.discoveredAt} · ${event.discoverySource ?? "Unknown source"}`}><Text value={event.rawSnapshot} /><p className="mt-2 text-xs text-slate-500">Reasons: {event.matchReasons ?? "—"} · Evidence: {event.matchEvidence ?? "—"}</p></Record>)}</Section></div>; }
function Section({ title, children }: { title: string; children: ReactNode }) { return <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="text-lg font-semibold text-slate-950">{title}</h2><div className="mt-4">{children}</div></section>; }
function Info({ label, value, href }: { label: string; value: string | null | undefined; href?: string | null }) { return <div><dt className="text-xs font-bold uppercase tracking-[0.1em] text-slate-500">{label}</dt><dd className="mt-1 break-words text-sm text-slate-800">{href ? <a href={href} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 underline hover:text-amber-700">{value}<ExternalLink className="h-3 w-3" /></a> : value || "—"}</dd></div>; }
function Record({ title, meta, children }: { title: string; meta: string; children: ReactNode }) { return <article className="border-b border-slate-100 py-4 last:border-0"><div className="flex flex-col justify-between gap-1 sm:flex-row"><strong className="text-sm text-slate-900">{title}</strong><span className="text-xs text-slate-500">{meta}</span></div><div className="mt-2 text-sm text-slate-700">{children}</div></article>; }
function Text({ value }: { value: string | null | undefined }) { return value ? <p className="mt-2 whitespace-pre-wrap break-words rounded-md bg-slate-50 p-3 text-sm leading-6">{value}</p> : <p className="mt-2 text-sm text-slate-400">No text recorded.</p>; }
function Empty({ value, text }: { value: boolean; text: string }) { return value ? <p className="rounded-md bg-slate-50 p-4 text-sm text-slate-500">{text}</p> : null; }
function Badge({ value }: { value: string | null | undefined }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${statusTone(value)}`}>{pretty(value)}</span>; }
