/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SectorsRouteImport } from './routes/sectors'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WhyChooseWossolExportRouteImport } from './routes/why-choose-wossol-export'
import { Route as AdminCatalogRouteImport } from './routes/admin/catalog'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminCatalogCompaniesRouteImport } from './routes/admin/catalog/companies'
import { Route as AdminCatalogCompaniesCompanyIdRouteImport } from './routes/admin/catalog/companies/$companyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsRoute = SectorsRouteImport.update({
  id: '/sectors',
  path: '/sectors',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyChooseWossolExportRoute = WhyChooseWossolExportRouteImport.update({
  id: '/why-choose-wossol-export',
  path: '/why-choose-wossol-export',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogCompaniesRoute = AdminCatalogCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AdminCatalogRoute,
} as any)
const AdminCatalogCompaniesCompanyIdRoute =
  AdminCatalogCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AdminCatalogCompaniesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/markets': typeof MarketsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sectors': typeof SectorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-choose-wossol-export': typeof WhyChooseWossolExportRoute
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/catalog/companies': typeof AdminCatalogCompaniesRouteWithChildren
  '/admin/catalog/companies/$companyId': typeof AdminCatalogCompaniesCompanyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/markets': typeof MarketsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sectors': typeof SectorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-choose-wossol-export': typeof WhyChooseWossolExportRoute
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/catalog/companies': typeof AdminCatalogCompaniesRouteWithChildren
  '/admin/catalog/companies/$companyId': typeof AdminCatalogCompaniesCompanyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/markets': typeof MarketsRoute
  '/opportunities': typeof OpportunitiesRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sectors': typeof SectorsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/why-choose-wossol-export': typeof WhyChooseWossolExportRoute
  '/admin/catalog': typeof AdminCatalogRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/catalog/companies': typeof AdminCatalogCompaniesRouteWithChildren
  '/admin/catalog/companies/$companyId': typeof AdminCatalogCompaniesCompanyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/markets'
    | '/opportunities'
    | '/privacy-policy'
    | '/sectors'
    | '/sitemap.xml'
    | '/why-choose-wossol-export'
    | '/admin/catalog'
    | '/admin/login'
    | '/admin/catalog/companies'
    | '/admin/catalog/companies/$companyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/markets'
    | '/opportunities'
    | '/privacy-policy'
    | '/sectors'
    | '/sitemap.xml'
    | '/why-choose-wossol-export'
    | '/admin/catalog'
    | '/admin/login'
    | '/admin/catalog/companies'
    | '/admin/catalog/companies/$companyId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/markets'
    | '/opportunities'
    | '/privacy-policy'
    | '/sectors'
    | '/sitemap.xml'
    | '/why-choose-wossol-export'
    | '/admin/catalog'
    | '/admin/login'
    | '/admin/catalog/companies'
    | '/admin/catalog/companies/$companyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  MarketsRoute: typeof MarketsRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SectorsRoute: typeof SectorsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhyChooseWossolExportRoute: typeof WhyChooseWossolExportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors': {
      id: '/sectors'
      path: '/sectors'
      fullPath: '/sectors'
      preLoaderRoute: typeof SectorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-choose-wossol-export': {
      id: '/why-choose-wossol-export'
      path: '/why-choose-wossol-export'
      fullPath: '/why-choose-wossol-export'
      preLoaderRoute: typeof WhyChooseWossolExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog/companies': {
      id: '/admin/catalog/companies'
      path: '/companies'
      fullPath: '/admin/catalog/companies'
      preLoaderRoute: typeof AdminCatalogCompaniesRouteImport
      parentRoute: typeof AdminCatalogRoute
    }
    '/admin/catalog/companies/$companyId': {
      id: '/admin/catalog/companies/$companyId'
      path: '/$companyId'
      fullPath: '/admin/catalog/companies/$companyId'
      preLoaderRoute: typeof AdminCatalogCompaniesCompanyIdRouteImport
      parentRoute: typeof AdminCatalogCompaniesRoute
    }
  }
}

interface AdminCatalogCompaniesRouteChildren {
  AdminCatalogCompaniesCompanyIdRoute: typeof AdminCatalogCompaniesCompanyIdRoute
}

const AdminCatalogCompaniesRouteChildren: AdminCatalogCompaniesRouteChildren = {
  AdminCatalogCompaniesCompanyIdRoute: AdminCatalogCompaniesCompanyIdRoute,
}

const AdminCatalogCompaniesRouteWithChildren =
  AdminCatalogCompaniesRoute._addFileChildren(
    AdminCatalogCompaniesRouteChildren,
  )

interface AdminCatalogRouteChildren {
  AdminCatalogCompaniesRoute: typeof AdminCatalogCompaniesRouteWithChildren
}

const AdminCatalogRouteChildren: AdminCatalogRouteChildren = {
  AdminCatalogCompaniesRoute: AdminCatalogCompaniesRouteWithChildren,
}

const AdminCatalogRouteWithChildren = AdminCatalogRoute._addFileChildren(
  AdminCatalogRouteChildren,
)

interface AdminRouteChildren {
  AdminCatalogRoute: typeof AdminCatalogRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCatalogRoute: AdminCatalogRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  MarketsRoute: MarketsRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SectorsRoute: SectorsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhyChooseWossolExportRoute: WhyChooseWossolExportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
